### PR TITLE
Fixes undeclared type errors when generating Swift enumerations

### PR DESCRIPTION
**Pull request by stefanceriu**
Fixes undeclared type errors when generating Swift enumerations, removed the Apollo module name as it doesn’t exist in this context.

```
Use of undeclared type 'Apollo'
Cannot convert value of type 'SomeType.Type' to expected argument type 'JSONDecodable.Type'
```

STRs
Try generating an API that makes use of enumerations.

Here's an example:

```
enum CarType {
    Sedan
    Hatchback
}

type Car {
    type: CarType
}

type Query {
    getCar: Car
}

schema {
    query: Query
}
```
Which would generate this [schema file](https://github.com/awslabs/aws-appsync-codegen/files/1963340/schema.json.zip)

Which I would then use with this GraphQL specification.
```
query GetSomeCar {
  getCar {
    type
  }
}
```

### CODE REVIEW

**Review by rohandubal — APPROVED** [review]

**Comment by rohandubal** [comment]
Thanks for the PR! I will merge this with the next release.

**Comment by huntermonk** [comment]
When can we expect the next release containing this? Thanks!

**Comment by minbi** [comment]
Merging for the release

**Comment by minbi** [comment]
I had to revert since the tests were not passing. I have added Travis CI so that you can see the failures with a new pull request.

**Pull request merged**
